### PR TITLE
add setuptools, add mukhery as maintainer

### LINKED ISSUE #72: @conda-forge-admin, please add user @mukhery
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by mukhery**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Resolves #72 and the issue with missing setuptools.

### CODE REVIEW

**Comment by mukhery** [comment]
@conda-forge-admin, please rerender

**Comment by mukhery** [comment]
@conda-forge/core can you please merge this so that I can help maintain this repo?

**Comment by mukhery** [comment]
@conda-forge/core could you please merge this?

**Comment by xhochy** [comment]
Please wait a week before contacting core.

**Comment by synapticarbors** [comment]
Let's give the current maintainers some time to review this. Core typically doesn't jump in unless there is no response after a week. Also, please address the linter's requests if you're making updates.

**Comment by synapticarbors** [comment]
Ok - sorry, I missed that one. Once the linter commit passes, I'm happy to merge this.

**Comment by synapticarbors** [comment]
It looks like `safetensors` is only built for a minimum of python 3.8 for its oldest version on conda-forge and 3.9 for its latest version. Our global `python_min` is 3.9, so it's probably best to use that

**Comment by mukhery** [comment]
> It looks like `safetensors` is only built for a minimum of python 3.8 for its oldest version on conda-forge and 3.9 for its latest version. Our global `python_min` is 3.9, so it's probably best to use that

Thanks for the assistance!

**Pull request merged**
